### ISSUE TITLE
unclear that this should also be public facing, it is not specific to your analysis in the VAE paper.. 

### ISSUE THREAD

**Issue by Christensen-Lab** [Christensen-Lab-Dartmouth/VAE_analysis#7]

**Comment by AlexanderTitus** [comment]
This is the repository from our first VAE [paper](https://www.scitepress.org/PublicationsDetail.aspx?ID=kxmWGvGaZh0=&t=1)

**Comment by AlexanderTitus** [comment]
I have updated the readme with a link to the paper
